### ISSUE TITLE
DFT+U support

### ISSUE THREAD

**Issue by sliutheory** [greschd/aiida-tbextraction#13]
Does this support DFT+U+SOC?

**Comment by greschd** [comment]
Yes, by setting the appropriate inputs to QE / Wannier90.

**Comment by sliutheory** [comment]
Thank you. I should have been more specific. 
Right now, it seems that the inputs for QE is configured directly in following way. 

    common_qe_parameters = orm.Dict(
        dict=dict(
            CONTROL=dict(etot_conv_thr=1e-4),
            SYSTEM=dict(noncolin=True, lspinorb=True, nbnd=180, ecutwfc=50),
        )
    )

Are you suggesting I also add U-related keywords such as Hubbard_U(i) in  SYSTEM as well?

**Comment by greschd** [comment]
Yes - with `aiida-quantumespresso` you can specify the Hubbard U as a dictionary, as follows:

```python
orm.Dict(
    dict=dict(
        CONTROL=dict(etot_conv_thr=1e-4),
        SYSTEM=dict(
            noncolin=True, 
            lspinorb=True, 
            nbnd=180, 
            ecutwfc=50,
            hubbard_u={'<kind_name>': <value>}
        ),
    )
)
```
