### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by ghost** [greschd/aiida-tbextraction#3]
Hi,

I came across with a problem of installing aiida-tbextraction: After installing aiida using conda channel, I used both "pip install aiida-tbextraction" and "python -m pip install aiida-tbextraction" to install this plugin code for aiida. Unfortunately, it was failed with the error message as shown in the attached picture:
![Error](https://user-images.githubusercontent.com/59998047/74926153-b818e480-53d5-11ea-9f40-ce72a4e162fb.PNG)

Could you indicate me something concerning how to figure out this installation problem ? Thanks.

Best,
Leon

**Comment by greschd** [comment]
Hi Leon,

Which versions of AiiDA and Python are you using?

The version of `aiida-tbextraction` on PyPI is a pre-release (alpha version), that was developed on the (then) current development branch of AiiDA.
I would suggest to instead install the `migrate_v1` branch from github instead. While this is also not a stable release, it is compatible with the released AiiDA 1.0 and 1.1 versions.

**Comment by Leon-1985** [comment]
> 
> 
> Hi Leon,
> 
> Which versions of AiiDA and Python are you using?
> 
> The version of `aiida-tbextraction` on PyPI is a pre-release (alpha version), that was developed on the (then) current development branch of AiiDA.
> I would suggest to instead install the `migrate_v1` branch from github instead. While this is also not a stable release, it is compatible with the released AiiDA 1.0 and 1.1 versions.

The aiida version: aiida-core-1.1.0
The python version: python-3.6.9

I used as well "python -m pip install aiida-tbextraction" to install the tbextraction version, as mentioned here: https://aiida-tbextraction.readthedocs.io/en/latest/tutorial/setup.html.

**Comment by Leon-1985** [comment]
BTW: I installed conda using https://anaconda.org/conda-forge/aiida-core as mentioned here: "https://anaconda.org/conda-forge/aiida-core". Once it was finished, I used "python -m pip install aiida-tbextraction" to install the tbextraction version as you mentioned. I am not sure what kind of mistakes are there.

**Comment by greschd** [comment]
Yeah, the version on PyPI definitely won't work with AiiDA 1.1.

You can try installing the `migrate_v1` branch with 
```
pip install git+https://github.com/greschd/aiida-tbextraction.git@migrate_v1
```

**Comment by Leon-1985** [comment]
> Yeah, the version on PyPI definitely won't work with AiiDA 1.1.
> 
> You can try installing the `migrate_v1` branch with
> 
> ```
> pip install git+https://github.com/greschd/aiida-tbextraction.git@migrate_v1
> ```

Thanks. I will make this try tonight and then let you know whether it is successful or not.

**Comment by Leon-1985** [comment]
Hi Gresch,

I tried the installation with your suggestion, i.e., "pip install git+https://github.com/greschd/aiida-tbextraction.git@migrate_v1". However, it does not work either. Here below is the error message attached. 
![Error](https://user-images.githubusercontent.com/59998047/75018458-3ab1aa80-548f-11ea-8884-864e4c5c67af.PNG)

**Comment by greschd** [comment]
Ah, you'd also need to install `aiida-wannier90` from the `develop` branch. However there you might want to wait, there should be an `aiida-wannier90` release very soon, probably next week.

**Comment by Leon-1985** [comment]
> Ah, you'd also need to install `aiida-wannier90` from the `develop` branch. However there you might want to wait, there should be an `aiida-wannier90` release very soon, probably next week.

Aha, that's why the installation got failed. I thought that  all mandatory dependences for the aiida-tbexteaction installation were already included into aiida. So I need to install aiida-wannier90 before aiida-tbextraction if I am not mistaken ?

**Comment by greschd** [comment]
Yes, `aiida-tbextraction` depends on various other packages besides `aiida-core`, as specified here: https://github.com/greschd/aiida-tbextraction/blob/develop/setup.json#L27

Usually this should be automatically handled by `pip`, but in the case of `aiida-wannier90` here the required version is not yet on PyPI.

**Comment by Leon-1985** [comment]
Hi Gresch,

I am asking that is it possible that aiida-wannier90 is ready being released this week ? 
Or is there any alternative ways to install and use just the current version of aiida-tbextraction ? Thanks !

Best,
Leon

**Comment by greschd** [comment]
There is no fixed release date for `aiida-wannier90`, but it should definitely be soon.

In the meantime, you can use the `develop` branch of `aiida-wannier90` also.

**Comment by greschd** [comment]
So the current installation instructions would be:

```bash
pip install git+https://github.com/aiidateam/aiida-wannier90.git@develop
pip install git+https://github.com/greschd/aiida-tbextraction.git@develop
```

Since this package is still in a "beta" stage, it might of course be a bit rough around the edges. So, please do let me know if you run into any more issues.

**Comment by Leon-1985** [comment]
> 
> 
> The current installation instructions would be:
> 
> ```shell
> pip install git+https://github.com/aiidateam/aiida-wannier90.git@develop
> pip install git+https://github.com/greschd/aiida-tbextraction.git@develop
> ```
> 
> Since this package is still in a "beta" stage, it might of course be a bit rough around the edges. So, please do let me know if you run into any more issues.

Sure, I will definitely let you know any bugs or issues if there are. At moment, the number one thing is to install this plugin software. :).

**Comment by Leon-1985** [comment]
> 
> 
> > The current installation instructions would be:
> > ```shell
> > pip install git+https://github.com/aiidateam/aiida-wannier90.git@develop
> > pip install git+https://github.com/greschd/aiida-tbextraction.git@develop
> > ```
> > 
> > 
> > Since this package is still in a "beta" stage, it might of course be a bit rough around the edges. So, please do let me know if you run into any more issues.
> 
> Sure, I will definitely let you know any bugs or issues if there are. At moment, the number one thing is to install this plugin software. :).

Unfortunately, this time fails again, even though I followed the above installation instructions.

![error](https://user-images.githubusercontent.com/59998047/75240673-060e5d80-57c5-11ea-8c11-2cc4e7323bb4.PNG)

**Comment by Leon-1985** [comment]
It seems that more additional dependencies need to be installed. But I am not very sure of this.

**Comment by greschd** [comment]
Aha! Now we're back to the original issue (but for a different package), which is that I didn't properly test things on systems where the default encoding is set to something other than ``utf-8``.

Can you please check if 
```bash
pip install git+https://github.com/greschd/aiida-tools.git
```
works for you? If so, I'll quickly make a bugfix release for the ``aiida-tools`` package.

**Comment by Leon-1985** [comment]
> pip install git+https://github.com/greschd/aiida-tools.git

Yes, it works successfully. And now you find the problematic issue ? Thanks.

**Comment by greschd** [comment]
Yes, the problem was that the encoding needed to be explicitly specified when opening a file. Can you now install ``aiida-tbextraction``, or are there any other issues?

**Comment by Leon-1985** [comment]
> 
> 
> Yes, the problem was that the encoding needed to be explicitly specified when opening a file. Can you now install `aiida-tbextraction`, or are there any other issues?

Now the installation of aiida-tbextraction is a bit improved. The only problem is attached below:
![error](https://user-images.githubusercontent.com/59998047/75243025-77500f80-57c9-11ea-8e78-e7e9274b69f2.PNG)

**Comment by Leon-1985** [comment]
It seems due to the incompatible issue caused by the aiida-core. Since so far I installed everthing in a virtual environment, to avoid any unexpected issues, maybe the best way is to remove the entire virtual environment and recreate a clean this environment and on top of it reinstall everything from scratch following our previous communications.

**Comment by greschd** [comment]
This shouldn't be an issue - it's because `aiida-vasp` has an explicitly specified AiiDA version as dependency.
But, since the current version of `aiida-tbextraction` uses Quantum ESPRESSO instead, the dependency on `aiida-vasp` should actually be removed.

**Comment by Leon-1985** [comment]
> 
> 
> This shouldn't be an issue - it's because `aiida-vasp` has an explicitly specified AiiDA version as dependency.
> But, since the current version of `aiida-tbextraction` uses Quantum ESPRESSO instead, the dependency on `aiida-vasp` should actually be removed.

Okay, you meant that i can ignore this error ? But the point is that I used VASP instead of QE for my DFT calculations. So can I use the current version of aiida-tbextraction ?

**Comment by Leon-1985** [comment]
Okay, anyway too much talk means nothing. Let me first try provided examples and if there are problems emerging, I will let you know ASAP.

**Comment by greschd** [comment]
> 
> 
> > This shouldn't be an issue - it's because `aiida-vasp` has an explicitly specified AiiDA version as dependency.
> > But, since the current version of `aiida-tbextraction` uses Quantum ESPRESSO instead, the dependency on `aiida-vasp` should actually be removed.
> 
> Okay, you meant that i can ignore this error ? But the point is that I used VASP instead of QE for my DFT calculations. So can I use the current version of aiida-tbextraction ?

The current version implements only the interface to QE. In principle it shouldn't be too difficult to adapt the previous version of the VASP interface. However, I don't have a valid license to run VASP these days, so no way of testing it.

**Comment by greschd** [comment]
> 
> Okay, anyway too much talk means nothing. Let me first try provided examples and if there are problems emerging, I will let you know ASAP.

Make sure to pull the latest version of the code -- I updated the examples a few minutes ago.

**Comment by Leon-1985** [comment]
You mean to create "New pull request" or something else ? if neither, then how to "make sure to pull the latest version of the code". Excuse me for such a "naive" question.

**Comment by Leon-1985** [comment]
Yes, I see you updated the examples (for qe) about half a hour ago. Do you still provide the examples for vasp ? If so, where I can get them ? Thanks.

**Comment by greschd** [comment]
> 
> You mean to create "New pull request" or something else ? if neither, then how to "make sure to pull the latest version of the code". Excuse me for such a "naive" question.

No, just to get the latest version of the examples.

>
> Yes, I see you updated the examples (for qe) about half a hour ago. Do you still provide the examples for vasp ? If so, where I can get them ? Thanks.

No, because I can't run VASP I could update neither the implementation nor the example to AiiDA 1.0. If you want, I can try updating the code anyway, for you to test. This will probably have to go back and forth a few times to find all the issues, though.

**Comment by ghost** [comment]
I am a bit sorry to bother you for such walking around a few times to find the relevant issues. But I do need the vasp examples for testing because I have no experience with QE to be frankly honest. Thanks for your understanding.

**Comment by ghost** [comment]
Hi, Precisely, I need the version v0.1.0a1 that was released on Jan, 2019. As far as I see from its document, it supports only VASP. However, I am not sure if I could install this version by simply following your previous installation instruction or you would have a different installation instruction. Thanks.

**Comment by greschd** [comment]
I wouldn't try installing v0.1.0a1 - that version was compatible with a development version of AiiDA itself; unfortunately the interface of AiiDA itself changed too much after that before 1.0, so now 0.1.0a1 is not really compatible with any usable version. Figuring out how to run that is probably more complicated than just updating the vasp-specific code to the new AiiDA version.

I'm working on this in the https://github.com/greschd/aiida-tbextraction/tree/add_vasp_compat branch - I guess I can at test it at least as creating the first inputs, before it actually runs VASP.

It will probably be a few weeks before I get around to working on this, though - since I can't run VASP anyway, it's not a very high priority for me.

If you're willing to try and fix that branch, though, I'm happy to give you some pointers.

**Comment by ghost** [comment]
Hi, 

Sorry for a bit late response because of a short week vacation. Yes, I am still interested in using this plugin with VASP and I will be appreciated with your pionters. So could you indicate me some howto ? Thanks !

Best,
Leon

**Comment by ghost** [comment]
Hello Gresch,

I am now getting back to this issue. This time I came across some problems to run the first example, for instance, how to set up the VASP and WANNIER codes and to configure the python environment.  I used "verdi" to do this but seems not working. Could you give me some instruction of HOWTO ? Thanks !

Best,
Leon

**Comment by greschd** [comment]
I'm not entirely sure I understand which part of the setup you are stuck on. Here's a how-to from the AiiDA documentation on running external codes: https://aiida.readthedocs.io/projects/aiida-core/en/latest/howto/run_codes.html

A prerequisite for this would be the general AiiDA introduction / setup guide.

Note that you need to independently install both VASP and Wannier90, so that you have the corresponding executables on the machine where you want to run the calculations.

**Comment by ghost** [comment]
Both VASP and Wannier90 were installed already. I think everything (aiida, tbextraction, tbmodes, bands-inspection, etc) was already installed there, see the screenshot below:
![image](https://user-images.githubusercontent.com/59998047/87784129-ffe15200-c835-11ea-8e1b-023093cdc359.png)
Then i used the command "verdi code setup" as instructed on the Aiida website to configure the code. Unfortunately, it fails with the error message "-bash: verdi: command not found".  Can you give me any suggestion to simplify the configuration and setup procedure as i am really getting confused. Thanks.

Best,
Leon

**Comment by ghost** [comment]
Sorry, the attached screenshot is not correct, which should be this:
![1](https://user-images.githubusercontent.com/59998047/87784555-d2e16f00-c836-11ea-8220-b4d0c7fcd647.PNG)

**Comment by greschd** [comment]
Hm, did you install `aiida-core` separately before? In any case, I think you should follow the install + setup instructions of AiiDA itself first.

**Comment by ghost** [comment]
I installed aiida-core before. What i followed is the link you sent to me: https://aiida.readthedocs.io/projects/aiida-core/en/latest/howto/run_codes.html.  I was just using verdi code setup, but the error message "-bash: verdi: command not found" pops out. 
Maybe you could me give me a list of installation sequence in order to use aiida-tbextraction. I got confused for a while. Thanks.

**Comment by ghost** [comment]
do you mind if i can have your email address then i can write all what i did before ?

**Comment by greschd** [comment]
The `verdi` command is part of `aiida-core`. If that doesn't work, you should follow (or repeat) the install guide for aiida-core.
